{% set name = "beakerx" %}
{% set version = "0.8.1" %}
{% set sha256 = "5ff78f59051f879dd1aba65764397e8fdd7a1a53b55511003f94cecabb76eb5e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  git_rev: {{ version }}
  git_url: https://github.com/twosigma/beakerx.git

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/b/beakerx/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  
build:
  number: 0
  skip: true  # [py2k]
  skip: true  # [win32]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - jupyter
    - pandas
  run:
    - python
    - jupyter
    - openjdk
    - maven
    - pandas
    - ipywidgets
    - widgetsnbextension

test:
  imports:
    - beakerx

about:
  home: http://github.com/twosigma/beakerx
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Beaker Extensions for Jupyter'

  description: |
    Beaker Extensions for Jupyter
  doc_url: https://github.com/twosigma/beakerx
  dev_url: https://github.com/twosigma/beakerx

extra:
  recipe-maintainers:
    - scottdraves
