{% set name = "beakerx" %}
{% set version = "0.5.0" %}
{% set sha256 = "f1b92a77b89b1ff20ebf814658d2f4ce67f998ae560c5806d10dc4f8b43eb264" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  git_rev: {{ version }}
  git_url: https://github.com/twosigma/beakerx.git

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/b/beakerx/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  
build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - jupyter
    - pandas
  run:
    - python
    - jupyter
    - openjdk
    - pandas
    - ipywidgets
    - widgetsnbextension

test:

about:
  home: http://github.com/twosigma/beakerx
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Beaker Extensions for Jupyter'

  description: |
    Beaker Extensions for Jupyter
  doc_url: https://github.com/twosigma/beakerx
  dev_url: https://github.com/twosigma/beakerx

extra:
  recipe-maintainers:
    - scottdraves
    - gnestor
