{% set name = "beakerx" %}
{% set version = "1.4.1" %}
{% set sha256 = "f4fcee4bd640a175783bfcf70fdd9f599b528808183bdf1993913e32bd759be7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  git_rev: {{ version }}
  git_url: https://github.com/twosigma/beakerx.git

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/b/beakerx/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  
build:
  number: 3
  skip: true  # [py2k]
  skip: true  # [win32]
  script: pip install --no-deps .
  entry_points:
    - beakerx = beakerx:run

requirements:
  build:
    - python
    - pip
  run:
    - python
    - notebook >=5.7.4
    - openjdk ==8.0.121
    - maven
    - py4j
    - numpy
    - pandas
    - ipywidgets >=7.0
    - widgetsnbextension
    - pytest
    - requests

test:
  imports:
    - beakerx
  commands:
    - beakerx -h

about:
  home: http://beakerx.com
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Beaker Extensions for Jupyter and Jupyter Lab'

  description: |
    Beaker Extensions for Jupyter and Jupyter Lab
  doc_url: http://beakerx.com
  dev_url: https://github.com/twosigma/beakerx

extra:
  recipe-maintainers:
    - LeeTZ
