{% set name = "beakerx" %}
{% set version = "0.15.1" %}
{% set sha256 = "f0bb07be19d363386531c3dcfa67d1fd2efd7596f7109f511508c55f6aa99f2a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  git_rev: {{ version }}
  git_url: https://github.com/twosigma/beakerx.git

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/b/beakerx/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  
build:
  number: 1
  skip: true  # [py2k]
  skip: true  # [win32]
  script: pip install --no-deps .
  entry_points:
    - beakerx = beakerx:run

requirements:
  build:
    - python
    - pip
  run:
    - python
    - notebook >=4.4.0
    - openjdk
    - maven
    - numpy
    - pandas
    - ipywidgets >=7.0
    - widgetsnbextension
    - pytest

test:
  imports:
    - beakerx
  commands:
    - beakerx -h

about:
  home: http://beakerx.com
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Beaker Extensions for Jupyter and Jupyter Lab'

  description: |
    Beaker Extensions for Jupyter and Jupyter Lab
  doc_url: http://beakerx.com
  dev_url: https://github.com/twosigma/beakerx

extra:
  recipe-maintainers:
    - scottdraves
