travis:
  secure:
    BINSTAR_TOKEN: Ql42A/6HQhYr6VW92g6K973JOLrVsr+JI60snHg9bUnrwEG4XBD+cq0+f/qPAlR2FJDLkuU8x4F/NxBGcOAhEXb7bM35bU/JPLFpSX4pns07ynFX/I6GxqHC5uZGAgCkdJcvKpjLW0C7tAssb7QiWbgN3DmismUCXXANzT0PXRPZtQQQInR8SVcZzam5vB5ls/iDeOtae5NVxPU0dW7Uf941cHbFc8v486XVx5buIedKNmq5aGAw9E3e4S14y1GtQT+ZH1/N8z2vH4GOmDQmDPcxxTPdSc+ikrlPkTrANuL9EGyQMiClyXXYhcrRu/6/AXg99m+PCJCfY1Y82JuLWyeyJsKTgXCg0fCycMuJz5QSeHuZ/j7F+DnFuiIqydlUFi7uUnTAXQQteD9renBokCJTVgyjbGxOBxprD/RuRHf0cjx5DLv8CGpArXSSWJ0Gd7cAAhV0TL2gPbEBOyuNW96ud5zFr/8+MHRIrcDcsfNTitudcqC/a/fYXINsHsS4gSIlRFq4E6W3QC57PSGW+zWcrW7WsmSIjnptz/2a/bwubOOsS8vuPV7yWKEYepVX6EC5fMTiSP6QanyKr8RntkplMZE6yAIt7F7wN04cByzCVqRwJFwgTaZstEoMZgs7OMGV/5Xx6VTKuE0mQAxIPwCdzkf9kCHuxPFvyvhieac=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
