appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Ceb62zo9XP1aILnCLRPTCo+TVdzzmItAin6IX+i3boUjAsExFYQqkgvqFREELzWOsYfzUcG01Kw8qCVCh/OuGWFKF3+wb1k/tl1JF9OrcEcdHDm+SrICJplE2gfsfXkLSw9vXAf6SZHMMuVrUYhe82FXF52Kkk7KzZhGG5bX6PuV5CpD1Jm7htqJld/yP1swgsxD0wDCAoM7KPL5DjzFvcKmcIQpODVte+a7+ZV2DDVVceia/lhOcupsthtZrsiOP9I7vPxbqPb2cJFNzCVnPvJURK/1E2JA7kl2fcQ3MnEkOGmC2MUaXJK5K0mXZynMhZXQaUh7PaZECjytb4jn7IhvNOO0PrcWMFc0c+n/4lWQDDGi2QzNjlVDieNqtAkMXkDY8pV3SkHUAU8UB76n6tCyiBINNsD1AJdHNNEGx5AqoVQvSP2A+3BOJDXZDkvQxWblVHgDzt+pd59nkE74cssmKYYRPhVVCPk7yqKQakNmdQmyK3Nn50jgBK7CUJfH38pc46ctxYTJ2w9NtANcE12vtYhWkQrUO1qrswtjthLDRIUsUTZ/NWKD7NYnKjupCM5EeoWstvd3ibKBDod3gaSA5zwgAQ0pKSWX55BOTXwFuJgruS4FclTulxoqWirXqQ/sSbnsF25byd2CbdH4WAyjMdoAEf5OfWfZA+Ad17w=}
