travis:
  secure:
    BINSTAR_TOKEN: QViV+EiUlfTLPJtCgkFCMy6AvmwyM/KYGTjHv3qBYMk3J+osZ08myrq44B8663utbvp/8ovVAGiYv4YpbD6HqFiVZUnNqG3Gw3mz8w3TQH8O3XmTutpZe7jrRlI61fEq4wvbX0uTixCEWnuA+dd7TgyiNqhZoK3SqRbmv9YHHSyr6ljtJq72yrmn6kysxP22FiEHtU8wk090nizN6QRhjwB1iXXCzS3tdjsQ8ZKCCHrdghOZzRCwIqYNXEBkmpauVh4+BaGE62h7zHZj8lNuVyKfeZZzZwyTbr2boUV4c/4uUqOSs9XYI1z77SRRPWD6bsd8tYtycXSu81DAoejSf+H6iiARPPID2eUYXczSHJI6Lu6LwgCv7etWf3s2WdWzT6V2y+kK1nlL4T33oPsxxKkVnRd/dK3iSXqUuxwyMPAkoFXfZfdH/gnTt7KTcxR4NP5n6VlcqP2+PrjW59pBtLJaUEB3Ij7ykfKvzsIbh9l9B5iliR09dl6H5dHncsshc5SI18rHlcI6pnXlB/V6pserUJZ+2kSvd/V2yZLc464D/fZER9W9UAykoPxVNcNCYpnWPQ7j2rxeXknnAJYSW7Aeech2z874vZCKC78LcgPtb1lCCqAQcNZX/etg/UpSmFdXST4In3cgUy38ibwQUnK3BSOrS5J1J2Req7XBhc8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: false
